# Layer configuration for meta-veraison-attestation

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-veraison-attestation"
BBFILE_PATTERN_meta-veraison-attestation = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-veraison-attestation = "10"

LAYERDEPENDS_meta-veraison-attestation = "core"
LAYERSERIES_COMPAT_meta-veraison-attestation = "walnascar"
